apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: /snap/kompose/19/kompose-linux-amd64 convert -c
    kompose.version: 1.21.0 (992df58d8)
  creationTimestamp: null
  labels:
    io.kompose.service: ddhcp-relay
  name: ddhcp-relay
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: ddhcp-relay
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.cmd: /snap/kompose/19/kompose-linux-amd64 convert -c
        kompose.version: 1.21.0 (992df58d8)
      creationTimestamp: null
      labels:
        io.kompose.network/baadist-default: "true"
        io.kompose.service: ddhcp-relay
    spec:
      volumes:
        - name: ddhcp-relay-volume
          persistentVolumeClaim:
            claimName: ddhcp-relay-pvclaim
      containers:
      - name: ddhcp-relay-container
        image: volt-container-demo
        imagePullPolicy: "IfNotPresent"
        env:
        - name: BAA_ADDRESS
          value: "baa.obbaa"
        - name: BAA_PORT
          value: "9292"
        - name: BAA_USERNAME
          value: "admin"
        - name: BAA_PASSWORD
          value: "password"
        - name: OBBAA_CONTROL_RELAY_ADDRESS
          value: "control-relay.obbaa"
        - name: OBBAA_CONTROL_RELAY_PORT
          value: "50055"
        - name: OLT_NAME
          value: "Altran_OLT"
        ports:
        - containerPort: 22
        securityContext:
                 privileged: true
        volumeMounts:
          - mountPath: /home/volt/backup
            name: ddhcp-relay-volume
      restartPolicy: Always
status: {}

