apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: /snap/kompose/19/kompose-linux-amd64 convert -c
    kompose.version: 1.21.0 (992df58d8)
  creationTimestamp: null
  labels:
    io.kompose.service: ddhcp-relay
  name: ddhcp-relay
  namespace: default
spec:
  type: NodePort
  ports:
  - name: "netconf"
    port: 6653
    targetPort: 22
    nodePort: 6653
  selector:
    io.kompose.service: ddhcp-relay
